Expandable section can be opened / closed from anywhere of the header
HSLdevcom/bultti-ui pull request #10
Opened 2020-11-27 06:11 UTC by Divinare

Closes: https://github.com/HSLdevcom/bultti/issues/84

We wanted to implement way to open/close from the whole expandable bar

- we dont want to open/close:
 - from the content of expandable bar
 - from any buttons inside expandable bar, places where this was prevented
    - post-inspections page at UserInspection section)
    - expandable bar's button on the right

2020-11-27 07:20 UTC, danieldunderfelt requested changes
Check the code comments.

2020-11-27 07:20 UTC, danieldunderfelt commented on src/inspection/InspectionUsers.tsx
> +              }}>
I would rather create a new callback, `onRefetchRelations`, which stops the event propagation, than make a separate stopPropagation function.

```suggestion
onClick={onRefetchRelations}>
```

2020-11-27 07:20 UTC, danieldunderfelt commented on src/inspection/InspectionUsers.tsx
> +
If necessary to stop propagation here, but I would rather have the ExpandableBox component catch and stop the propagation and not have to do that separately in all components which use the expandable box.

```suggestion
  const onRefetchRelations = useCallback((e: React.MouseEvent) => {
    e.stopPropagation()
    refetchRelations()
  }, [refetchRelations])

```

2020-11-27 07:20 UTC, danieldunderfelt commented on src/common/components/ExpandableSection.tsx
>          <HeaderRow>
Would it be effective to set the stopPropagation handler on HeaderRow, and have it catch and stop propagation from all buttons in the header? This would make it unnecessary to stop propagation in the button handlers separately.

2020-11-27 09:15 UTC, Divinare commented on src/common/components/ExpandableSection.tsx
>          <HeaderRow>
This was what I initially wanted but didn't figure out a way. Now I just commited a solution where you don't need to handle stop propagation in button handlers!

2020-11-27 09:16 UTC, Divinare commented on src/inspection/InspectionUsers.tsx
> +
No longer have to stop propagation here

2020-11-27 09:17 UTC, Divinare commented
Review fix done! Now it's only ExpandableSection's responsibility to handle stopPropagations.

Yes, there are two methods (the click handlers onClickHeaderRow, onClickExpandToggle) that call setExpanded(), but I think that way the code is cleaner

2020-11-30 07:10 UTC, danieldunderfelt requested changes
A few comments and suggestions.

2020-11-30 07:10 UTC, danieldunderfelt commented on src/common/components/ExpandableSection.tsx
> +        forOwn((e.target as Element).classList, (value) => {
I would rather check that the `tagName` of the target isn't a `button`, `input`, or `a`. The className is not reliable.

2020-11-30 07:10 UTC, danieldunderfelt commented on src/common/components/ExpandableSection.tsx
> +          <ExpandToggle expanded={expanded} onClick={onClickExpandToggle}>
No need to have an event handler here as you are already listening for click events in the parent.

2020-11-30 07:10 UTC, danieldunderfelt commented on src/common/components/ExpandableSection.tsx
>              <HeaderContentWrapper expanded={expanded}>
Suggestion: move the element type check to a click handler on this element from `onClickHeaderRow` and stopPropagation if necessary?

2020-11-30 11:41 UTC, Divinare commented on src/common/components/ExpandableSection.tsx
> +          <ExpandToggle expanded={expanded} onClick={onClickExpandToggle}>
If I take this click handler out, then yes it does trigger the parent's click handler. But the problem is className is not 'ExpandableSection' so setExpanded() won't get called.

2020-11-30 11:44 UTC, Divinare commented on src/common/components/ExpandableSection.tsx
> +        forOwn((e.target as Element).classList, (value) => {
That is not reliable either though, there can still be a child with a className 'ExpandableSection' which type is `div` and then this would get triggered from that. As long as there is no child with className 'ExpandableSection' this isn't a problem. I think the most secure way might be to use 'ref' somehow

2020-11-30 13:39 UTC, Divinare commented
Now we count the number of classes found from click event. Couldn't find any other secure way to ensure this

2020-11-30 13:47 UTC, Divinare commented on src/common/components/ExpandableSection.tsx
>              <HeaderContentWrapper expanded={expanded}>
Tried having one method with:
```
onClick={(e) => onClickHeaderRow(e)({ isForced: false })}
if (isForced) {
  setExpanded((currentVal) => !currentVal)
  e.stopPropagation()
  return
}
```

But I prefered having two methods instead of passing booleans and having an additional if statement there

2020-12-01 06:05 UTC, danieldunderfelt requested changes
This is my suggestion for a very simple implementation. I should have done this from the start:

https://github.com/HSLdevcom/bultti-ui/pull/13/files

Two click handlers and one is just for stopping propagation if the clicked element is a button. Checking the className is not necessary.

2020-12-01 06:05 UTC, danieldunderfelt commented on src/common/components/ExpandableSection.tsx
> +        forOwn((e.target as Element).classList, (value) => {
TagName is very reliable. We should always make clickable elements with `button`, except in this case where we have to put a click handler on a div. But all clickable elements within the header will always be either button, a, or input. We can add to this list if necessary.
I would say you never have to look at the className in React if you're using styling solutions such as styled-components as we are here.
Check the suggestion in the main thread of this PR.

2020-12-01 06:05 UTC, danieldunderfelt commented on src/common/components/ExpandableSection.tsx
>              <HeaderContentWrapper expanded={expanded}>
No, we don't. Check the suggestion in the main thread of this PR.

2020-12-01 06:32 UTC, Divinare commented
Lets use the suggestion here: https://github.com/HSLdevcom/bultti-ui/pull/13

With knowing of that conviention of using always <Button /> instead of <div />, that solution is ok

2020-12-01 06:32 UTC, closed without merging