424 unit settings and max age calculation
HSLdevcom/bultti-ui pull request #125
Opened 2021-08-04 09:59 UTC by danieldunderfelt

Closes HSLdevcom/bultti/#424

Add option period start date and option max age increase method fields to procurement unit edit form. Update the data shown in the procurement unit expanding box header. Calculate the max age of the units using the new props.

Server PR: https://github.com/HSLdevcom/bultti/pull/428

2021-08-17 10:03 UTC, Divinare requested changes
Code review done! Didn't test properly yet

2021-08-17 10:03 UTC, Divinare commented on src/procurementUnit/procurementUnitUtils.ts
> +export function calculateMaximumAverageAge(
I strongly suggest calculating this value only in BE and using procurementUnit.maximumAverageAge

2021-08-17 10:13 UTC, Divinare commented on src/text/fi.json
> +  "procurementUnit_ageRequirementWithOptions": "Maksimi keski-ikä optiokorotuksilla",
Suggestion:
Maksimi keski-ikä optiokorotuksilla (tällä hetkellä)

For me it's not quite clear that the current date affects the value. In future, after we pass the option year start date, option max age starts increasing

2021-08-17 10:54 UTC, Divinare commented
Testing:

The numbers seems to be incorrect. As testing in 17.8.2021:

Optio-kauden alkupvm 16.8.2019 should be 8,5, was 8
Optio-kauden alkupvm 17.8.2019 should be 8,5, was 8
Optio-kauden alkupvm 18.8.2019 should be 8 , was 8

2021-08-17 11:49 UTC, Divinare commented on src/procurementUnit/procurementUnitUtils.ts
> +export function calculateMaximumAverageAge(
Seems like this value is really wanted in UI. How about making a resolver and getting this value that way from backend?

2021-08-17 12:00 UTC, Divinare commented
Review done!

2021-08-18 05:58 UTC, danieldunderfelt commented on src/procurementUnit/procurementUnitUtils.ts
> +export function calculateMaximumAverageAge(
Yes, good idea. Fixed!

2021-08-18 06:00 UTC, danieldunderfelt commented on src/text/fi.json
> +  "procurementUnit_ageRequirementWithOptions": "Maksimi keski-ikä optiokorotuksilla",
Might be a bit long... maybe as a ? text.

2021-08-18 06:02 UTC, danieldunderfelt commented
> A) The numbers seems to be incorrect. As testing in 17.8.2021

The option period is never compared to the _current_ date. When on the "Muokkaa kilpailukohteet" page, the option period end date is the start of the season (for lack of a better thing to use). When on the edit pre-inspection page, the option period end date is the start of the inspection period.

2021-08-18 06:04 UTC, danieldunderfelt commented on src/text/fi.json
> +  "procurementUnit_noOptions": "Ei optiota",
Sure, I'll use that.

2021-08-18 07:07 UTC, Divinare commented on src/text/fi.json
> +  "procurementUnit_ageRequirementWithOptions": "Maksimi keski-ikä optiokorotuksilla",
Yeah, I guess the current one is OK. It will most likely be changed in the future anyway

2021-08-19 07:43 UTC, Divinare commented
The option year should update when calendar is updated. There is an apollo cache issue, otherwise this PR is OK!

Steps something like
1) Set option year date for some procurementUnit that has not been touched
2) Switch season
3) --> option year doesn't up update correctly. It updates once you change option year a bit
4) But now, if switch between seasons, it suddenly works because of apollo caches the calculated option year

---> this should be fixed that it would always calculate and not use apollo cache

2021-08-19 09:26 UTC, Divinare approved these changes
LGTM, cache issue seems to be solved!

2021-08-19 09:26 UTC, merged