326 Block operators from removing execution requirement equipment
HSLdevcom/bultti-ui pull request #129
Opened 2021-08-10 08:47 UTC by danieldunderfelt

Closes HSLdevcom/bultti#326

Hides equipment remove button in execution requirements for operator users.

Server PR:

2021-08-17 13:01 UTC, Divinare commented
Testing:

A) Ticket description says: Tämän tiketin yhteydessä muokataan myös painikkeen "virkistä kalustoluettelosta" teksti "palauta alkuperäinen kalustoluettelo". --> this wasn't changed

2021-08-17 13:07 UTC, Divinare requested changes
Testing:

A) Ticket description says: Tämän tiketin yhteydessä muokataan myös painikkeen "virkistä kalustoluettelosta" teksti "palauta alkuperäinen kalustoluettelo".
--> this wasn't changed

B) Ticket description says: "EDIT: Halutaan tosiaan vain kohteen ajoneuvon prosenttiosuuden muokkaus estää. Edelleen liiikennöitsijä saa lisätä / poistaa kalustoa."
--> as I logged in with operator account, I wans't able to remove

C) "Poista suoritevaatimus" button is visible for Operator. Clicking it as Operator threw a long error.  Shouldn't this button not be there? Also btw do why even have this button?

2021-08-19 09:27 UTC, danieldunderfelt commented
> A) Ticket description says: Tämän tiketin yhteydessä muokataan myös painikkeen "virkistä kalustoluettelosta" teksti "palauta alkuperäinen kalustoluettelo".

Updated now!

> B) Ticket description says: "EDIT: Halutaan tosiaan vain kohteen ajoneuvon prosenttiosuuden muokkaus estää. Edelleen liiikennöitsijä saa lisätä / poistaa kalustoa."

Further specs were talked about later, I mentioned this in the PR description.

> C) "Poista suoritevaatimus" button is visible for Operator. Clicking it as Operator threw a long error. Shouldn't this button not be there? Also btw do why even have this button?

The button is gone.

2021-08-19 10:25 UTC, Divinare approved these changes
LGTM!

2021-08-19 10:25 UTC, merged