WIP: 95 fix date fields into dropdown
HSLdevcom/bultti-ui pull request #40
Opened 2021-01-21 14:08 UTC by Divinare

2021-01-26 12:26 UTC, danieldunderfelt requested changes
Mostly good, but some comments.

A big theme is using the date-fns Interval interface to represent all date ranges, even for functions that don't come from date-fns. Entities (Inspection and InspectionDateRange) should of course keep their current date properties as they are, I'm only talking about how date ranges are handled in the code. The value of `start` and `end` on the ranges should be Date where possible, except in cases where there would be a lot of converting back and forth between Date and string.

2021-01-26 12:26 UTC, danieldunderfelt commented on src/inspection/inspectionSelectDates.tsx
> +              endDate: inspectionInput.inspectionEndDate!,
Use date-fns Interval interface here too. OK to use strings as values though.

2021-01-26 12:26 UTC, danieldunderfelt commented on src/inspection/inspectionSelectDates.tsx
> +const _getPreInspectionDateOptions = (): DateOption[] => {
Standalone functions should be defined with the `function` keyword.

And drop the underscore, I don't like it, except for utility properties on objects.

2021-01-26 12:26 UTC, danieldunderfelt commented on src/inspection/inspectionSelectDates.tsx
> +  endDate.setDate(endDate.getDate() + 90)
Javascript's Date object is horrible and we should use date-fns functions wherever possible. I have no idea what's going on here. Suggestion:

```suggestion
  let endDate = addSeconds(startDate, 90)
```

Substitute "addSeconds" with the function that corresponds to what unit the "90" is supposed to be.

2021-01-26 12:26 UTC, danieldunderfelt commented on src/inspection/inspectionSelectDates.tsx
> +  })
This Is The Way.

2021-01-26 12:26 UTC, danieldunderfelt commented on src/inspection/inspectionSelectDates.tsx
> +    let label = readableDateRange({ startDate, endDate })
Date-fns Interval interface for all of this too!

2021-01-26 12:26 UTC, danieldunderfelt commented on src/inspection/inspectionSelectDates.tsx
> +): DateOption[] => {
Same thing as above, use `function` and drop the underscore.

2021-01-26 12:26 UTC, danieldunderfelt commented on src/inspection/inspectionSelectDates.tsx
> +  let dateOneMonthAgo = sub(new Date(), { months: 1 })
I'd use `subMonths()` but this is not really wrong either.

2021-01-26 12:26 UTC, danieldunderfelt commented on src/util/formatDate.ts
> +}
Good to encapsulate this in a function, but I wouldn't use "bultti" in the function name. Also use the `AcceptedDateFormat` arg type and `getDateObject` to make the function more flexible.

And yes we should probably replace all `format(dateStr, DATE_FORMAT)` with this function.

2021-01-27 06:41 UTC, Divinare commented on src/executionRequirement/PostInspectionExecutionRequirements.tsx
> +            readableDateRange({ startDate: req.startDate, endDate: req.endDate })
I think startDate and endDate are better variable names but changed this anyway if it's a convention

2021-01-27 06:59 UTC, Divinare commented on src/common/input/Dropdown.tsx
> +  items: any[] // any object (remember to pass itemToString, itemToLabel), array, { field, value } object
Yup, typing inspead of any is always nice. But sometimes you need to use `any` like when making a generic update value func from a form. Having much different prop types increases complexity though

2021-01-27 07:06 UTC, Divinare commented on src/inspection/inspectionSelectDates.tsx
> +  })
Yeah but I wouldn't use the same variable names just because a good library uses them. I think variable names should specify what `type` they are so you don't have to look around them. But yeah it's not that a big deal here.

2021-01-27 07:08 UTC, Divinare commented on src/inspection/inspectionSelectDates.tsx
> +  })
And yeah I don't mean that is always the case :D

sometimes it's just ok to do this for example:
```
dateOptions.sort((a: DateOption, b: DateOption) => {
      return a.value.startDate.getTime() < b.value.startDate.getTime() ? -1 : 1
})
    ```

2021-01-27 07:09 UTC, Divinare commented on src/inspection/inspectionSelectDates.tsx
> +    let label = readableDateRange({ startDate, endDate })
It's enough to say it in 1 place, I will then change it everywhere else :>

2021-01-27 07:16 UTC, Divinare commented on src/inspection/inspectionSelectDates.tsx
> +): DateOption[] => {
I see nothing wrong with the underscore though. It indicates that the func is a private function declared in this file. It's just a helper function, nothing interesting there. Also I put it to the end of the file so that you have less things to look at.

2021-01-27 07:23 UTC, Divinare commented on src/inspection/inspectionSelectDates.tsx
> +): DateOption[] => {
I agree on using function though!

2021-01-27 07:41 UTC, Divinare commented on src/inspection/inspectionSelectDates.tsx
> +  let dateOneMonthAgo = sub(new Date(), { months: 1 })
Using subMonths(), maybe it's slightly more readable.

2021-01-27 10:53 UTC, Divinare commented
Review fixes & suggestions done. There are some more suggestions that aren't dealt with (check PR description above)

2021-01-27 12:59 UTC, danieldunderfelt requested changes
A few comments still! But it is looking good.

2021-01-27 12:59 UTC, danieldunderfelt commented on src/inspection/inspectionSelectDates.tsx
> +    }
I would still prefer this if possible.

2021-01-27 12:59 UTC, danieldunderfelt commented on src/inspection/inspectionSelectDates.tsx
> +    }
And this!

2021-01-27 12:59 UTC, danieldunderfelt commented on src/inspection/inspectionSelectDates.tsx
> +  })
My point is that if there are places in the code where you define a date range as an object, I would prefer if we used the same interface from date-fns. So if you were going to do this:

```
let range = {
  startDate: dateValue,
  endDate: dateValue
}

```

Instead do this:

```
let range = {
  start: dateValue,
  end: dateValue
}

```

That way, every date range defined in the app adheres to the same interface. Of course, if the object is _not_ a date range (eg it has other props too) then startDate and endDate is ok to keep.

2021-01-27 12:59 UTC, danieldunderfelt commented on src/inspection/inspectionSelectDates.tsx
> +function _getPostInspectionDateOptions(
```suggestion
function getPostInspectionDateOptions(
```

2021-01-27 12:59 UTC, danieldunderfelt commented on src/inspection/inspectionSelectDates.tsx
> +function _getPreInspectionDateOptions(): DateOption[] {
```suggestion
function getPreInspectionDateOptions(): DateOption[] {
```

2021-01-27 13:01 UTC, danieldunderfelt commented on src/common/input/Dropdown.tsx
> +  items: any[] // any object (remember to pass itemToString, itemToLabel), array, { field, value } object
Yeah let's not overcomplicate it.

2021-01-27 13:03 UTC, danieldunderfelt commented on src/inspection/inspectionSelectDates.tsx
> +): DateOption[] => {
I just think the underscore is very ugly and unnecessary, I avoid it like the plague. If it's a private helper it is enough to just not export it.

2021-01-27 14:05 UTC, Divinare commented
Review fixes done!

2021-01-28 12:18 UTC, Divinare commented
Review fixes done again.

2021-01-28 12:24 UTC, danieldunderfelt approved these changes
Great work!

2021-01-28 12:31 UTC, merged