85 table component fixes
HSLdevcom/bultti-ui pull request #50
Opened 2021-02-12 09:11 UTC by Divinare

Closes: https://github.com/HSLdevcom/bultti/issues/85

CSS Note: I wish I could disable hover for options with selectedPageOptionStyles style object. Didn't figure out an easy way to do that.

How the idea works:
You can pass to <Table>:
visibleRowCountOptions={[]} // to show all elements
visibleRowCountOptions={[5, 10]} // to show 5 / 10 elements per page options
visibleRowCountOptions={undefined} // when not passing visibleRowCountOptions, default 10, 20, 50 options are shown
selectedRowCountOption={20} // option 20 is selected by default
selectedRowCountOption={19} // throws an error if option 19 is not found

Note: Logic changed a bit when refactored remove button related things:

{!isEditingRow && removeItem && ( <RowRemoveButton>...
--> is now just
{onRemoveRow && ( <RowRemoveButton>...
didn't see a reason why we would want to hide remove button when editing row

2021-02-16 08:46 UTC, danieldunderfelt requested changes
It works, but I have a few comments.

2021-02-16 08:46 UTC, danieldunderfelt commented on src/report/Report.tsx
> +            }
This is not a better solution. It is not good to just write state + 1 as state updates are asynchronous. There was a reason for using `setState( currentState => { ... })`. Then it would be good to encapsulate this functionality in a callback, much like the one you removed. This component also updates frequently so using `useCallback` is a good idea.

2021-02-16 09:02 UTC, Divinare commented on src/report/ReportPaging.tsx
> +  onSetPageSize: (targetPageSize: number) => void
That's true, didn't think this way: "This component should not get to decide if the functions can return stuff or not". If you always think like this, there is never a place to use void right?

In some case `void` might cause an error the passed function returns something when used in a different way

However, using `void` might expose some flaw in logic. If child defines "give me a function to call that doesn't return anything" and then it gets accidentally given a function that returns something -> developer gets notified of his mistake

Hard to balance between those two. It depends on "how crystal clear is it that the given function doens't return anything" and in here if I knew about ReportPaging, I would expect user to pass func returning nothing. It also adds some readability.

2021-02-16 09:08 UTC, Divinare commented on src/report/Report.tsx
> +            }
Better would be:

```
let setPageCb = useCallback(setPage)
<ReportPaging
   setPage={setPageCb}
```

2021-02-16 09:17 UTC, danieldunderfelt commented on src/report/ReportPaging.tsx
> +  onSetPageSize: (targetPageSize: number) => void
It depends on if the function cares about the return value or not. There may be cases where the function needs the cb to not return anything, and for those cases it can set a => void restriction. But I don't think it should do that if it doesn't care about the return value. A logic flaw cannot exist for a return value that is ignored.

Void can also be used when defining functions if they should not return anything. Also, in new Typescript versions, Promise<void> must be used for promises which don't return anything. So void is not useless! But it should also not be used to set unnecessary restrictions.

2021-02-16 14:33 UTC, Divinare commented on src/report/ReportPaging.tsx
> +  onSetPageSize: (targetPageSize: number) => void
I agree! This is why I used void here: "Void can also be used when defining functions if they should not return anything."

But hmm, for the science I tried the following code:

Report.tsx
```
  let onSetPageCb = (targetPageNumber: number): number => {
    setPage({
      page: targetPageNumber,
      pageSize: page.pageSize,
    })
    return 5
  }
  onSetPage={onSetPageCb}
```

ReportPaging.tsx props
```
onSetPage: (targetPageNumber: number) => void
```

And the code compiled! So using void doesn't add a restriction here.... So the difference between void and unknown is small, maybe as you said, it is just there to help when using promises or when you want to say:

void: "there should be no return value of this given function, I won't use it"
unknown: "i dont care if there is a return value, I won't use it"

Btw for the science vol 2:
onSetPage: (targetPageNumber: number) => unknown
let x: number = onSetPage(5) as number; <-- compiles

onSetPage: (targetPageNumber: number) => void
let x: number = onSetPage(5) as number; <-- doesnt compile
let x: number = onSetPage(5) as unknown as number; <-- compiles :P

2021-02-16 14:39 UTC, Divinare commented on src/equipment/EquipmentList.tsx
> +    let [isEquipmentShownInGroup, setIsEquipmentShownInGroup] = useState(true)
Well, I think `isEquipmentShownInGroup` is better even though it's longer. The word "grouped" is so odd it requires more explanation in my opinion

2021-02-16 14:42 UTC, Divinare commented on src/equipment/EquipmentList.tsx
> +    let [isEquipmentShownInGroup, setIsEquipmentShownInGroup] = useState(true)
isEquipmentClustered sounds cleared to my ear :D

2021-02-17 06:49 UTC, danieldunderfelt commented on src/report/ReportPaging.tsx
> +  onSetPageSize: (targetPageSize: number) => void
> "Void can also be used when defining functions if they should not return anything."

Yes, but we are not defining functions here, that is the issue. We're defining **props** for a component, and if they don't care about the return value of the callback, they should not put a restriction on it.

It's really weird that it wouldn't complain in that example, I need to test that for myself. Maybe our Typescript config is too loose?

> void: "there should be no return value of this given function, I won't use it"

Is not correct. It's more like:

> void: "there should be no return value of this given function, *I will not work correctly if there is*"

And I mean this only when defining props or types that _consume_ a function. When defining a function itself it is clear that `void` means to return value.

2021-02-17 07:05 UTC, danieldunderfelt approved these changes
LGTM

2021-02-17 07:05 UTC, merged