WIP 58 sanctions UI
HSLdevcom/bultti-ui pull request #51
Opened 2021-02-15 08:38 UTC by danieldunderfelt

UI for post-inspections sanctioning WIP

Issue: HSLdevcom/bultti#58

BE PR: HSLdevcom/bultti#193

2021-02-19 14:21 UTC, Divinare commented
Review testing: it works, nice! \o/

Some enhancements/bug fixes that I found while testing (note: not everything has to be fixed in this card!):

* Table pagination not working properly
  * Rows per line option not working
    1) Go to procurementUnit page
    2) Open a vehicleList with 20++ vehicles
    3) try different "rows per page" options. When I have 54 vehicles, isGrouped=false, rows per page 50, page 1 shows only 4 vehicles and page 0 shows 0
  * if using UI pagination, remove table pagination if you have <= 20 rows
    * table pagination: max rows per page: rows.length

* Btw as a personal preference, button texts "Edellinen" and "Seuraava" could be bigger, even 1 rem or that 0.875 is fine for me.

* New task idea: cronjob to preload HFP from inspection time ranges? Then we can extract HFP loading out of POST inspection page

* I was able to create POST inspection before creating PRE inspection, should there be some kind of selection "attach PRE inspection to POST inspection" before starting to fill POST inspection form? Now it requires me to somehow attach PRE inspection to POST inspection

* PRE/POST inspection page: without PRE/POST inspections, the page says nothing, shows just an empty page. Add a notification "Ennakkotarkastuksia ei löytynyt" (because how a user knows if it's loading / bugged / really has no PRE/POST inspections -> card?

* New task idea: pre check & guidance before opening POST inspection form. That guidance would give instructions to the user to setup everything correctly so that he doesn't have to go back and forth between POST inspection page and other pages!
  * Problems that could be avoided by this:
    * Countered a usability problem 1: when creating a pre inspection, I set name, date and departureBlocks. Now it says vehicleList is missing
    * Countered a usability problem 2: when creating a pre inspection, I set name, date and departureBlocks. Now it says contract is missing even though I have it
    * If contracts are invalid, progress should be prevented with note "fix contracts" and after contracts are fixed & valid, user should be able to progress forward

* PRE Inspection: start & end date should be empty by default (user has to select date range)
   * generate date options from season start to season end
   * same bug in POST inspection

* Edit inspectionDates: prevent removing inspectionDates that are already used
  * Say which operator is using and blocking inspectionDates removal

* rename % Osuus -> Suunniteltu % Osuus

* Add (?) hintText after column names with some explanation

* Go back from sanctioning functionality is missing

Some notes here ^, you can decide whether you want to fix them here or make a new card of them!

2021-02-22 04:54 UTC, danieldunderfelt commented
Tasks belonging to this PR:

- Going back to draft state from sanctioning
- Fix problem where missing contract info crashed the collection of sanctions. It should have used a default value instead. Contract can be validated separately with the Inspection Validation feature.

The rest of the observations and ideas can be made as separate tickets. I made ticket HSLdevcom/bultti#203 for preloading HFP data, that is a very good idea.

> That guidance would give instructions to the user to setup everything correctly so that he doesn't have to go back and forth between POST inspection page and other pages!

This is a good thought, but in real production use everything will be done in the correct order. It's only in dev that we're jumping between the features.

> Countered a usability problem 1: when creating a pre inspection, I set name, date and departureBlocks. Now it says vehicleList is missing

I'm not sure that a "vehicleList" is, do you mean equipment catalogue or execution requirement equipment? The same comment as above applies here too, the user will have done everything in the correct order in production use.

> Countered a usability problem 2: when creating a pre inspection, I set name, date and departureBlocks. Now it says contract is missing even though I have it

Probably just an unrefreshed inspection validation. Contracts are also set up waaaay ahead of making any inspections, I don't see a problem for production.

> If contracts are invalid, progress should be prevented with note "fix contracts" and after contracts are fixed & valid, user should be able to progress forward

Yes, some contract rules should maybe be validated, but it is the user's responsibility to upload correct contracts and check them in the contract editor view. Code that uses rules should have default values to prevent crashes.

> I was able to create POST inspection before creating PRE inspection, should there be some kind of selection "attach PRE inspection to POST inspection" before starting to fill POST inspection form? Now it requires me to somehow attach PRE inspection to POST inspection

The current production pre-inspection for the season will be automatically selected. Draft post-inspections can still be created.

Other observations and ideas that I didn't comment on are good ideas and should be fixed in separate issues.

2021-02-22 08:25 UTC, danieldunderfelt commented
PR updated!

Fixed (both here and in BE):

- Going back to draft state from sanctioning, with removal of sanction rows and related user-inspection relation type.
- Fix problem where missing contract info crashed the collection of sanctions. It should have used a default value instead.
- Removed sanction button when in sanctioning
- Fixed some localisations

2021-02-22 10:13 UTC, Divinare commented
Some more testing

* Open pre inspection should imo open to a new tab. Now if you want to check it out, you are forced to leave the page where you are editing POST inspection
* I think pre/post inspection pages have too many togglable containers. I understand toggle in equipment list but not in elements like "Tarkastuksen tiedot" or "Suoritevaatimukset
   --> make suoritevaatimukset without togglable container. Card -> ?
   --> merge 2x Tarkastuksen tiedot + the container with "tarkastuksen nimi" as one untogglable container labeled as "Tarkastuksen tiedot". Card -> ?
* Suoritevaatimukset table: no need "Rivejä per sivu" because you only have 10 rows there
* Suoritevaatimukset table: after clicking "Luo suoritevaatimukset ennakkotarkastuksesta", it still says the same "Luo suoritevaatimukset ennakkotarkastuksesta" even though I don't have to click it. Could text be "Päivitä suoritevaatimukset ennakkotarkastuksesta"?
    * Why is there a button "Poista tarkastuksen suoritevaatimukset"?
* "Aloita sanktiointi" button is clickable even though it says "Joiltakin kohteilta puuttuu suoritevaatimus."
  * Clicking didn't do anything though, so only need to disable the button
* Clicking "Aloita sanktiointi" doesn't do anything even though everything seems ok (no red error texts)
  * I think this might be due to that I currently have 2x POST inspections with the same "tarkastusjakso" and btw both are "versio 0" - is that a bug?
  
  Please make for example a bullet point list with suggested features + links to cards to implement them

2021-02-22 11:10 UTC, danieldunderfelt commented
> Open pre inspection should imo open to a new tab. Now if you want to check it out, you are forced to leave the page where you are editing POST inspection

The user can middle click all links.

> I think pre/post inspection pages have too many togglable containers. I understand toggle in equipment list but not in elements like "Tarkastuksen tiedot" or "Suoritevaatimukset
--> make suoritevaatimukset without togglable container. Card -> ?
--> merge 2x Tarkastuksen tiedot + the container with "tarkastuksen nimi" as one untogglable container labeled as "Tarkastuksen tiedot". Card -> ?

Sure, if you think it's worthwhile to do. I'm not against it :D

> Suoritevaatimukset table: no need "Rivejä per sivu" because you only have 10 rows there

Let's continue work on the tables in another PR.

> Suoritevaatimukset table: after clicking "Luo suoritevaatimukset ennakkotarkastuksesta", it still says the same "Luo suoritevaatimukset ennakkotarkastuksesta" even though I don't have to click it. Could text be "Päivitä suoritevaatimukset ennakkotarkastuksesta"?

Sure, but the action is the same.

> Why is there a button "Poista tarkastuksen suoritevaatimukset"?

If you want to remove them. You need to recreate them again though. This is probably mostly useful in dev :D

> "Aloita sanktiointi" button is clickable even though it says "Joiltakin kohteilta puuttuu suoritevaatimus." Clicking didn't do anything though, so only need to disable the button

Yes

> Clicking "Aloita sanktiointi" doesn't do anything even though everything seems ok (no red error texts).

It takes a while, be patient. I agree there should probably be a processing step here.

> I think this might be due to that I currently have 2x POST inspections with the same "tarkastusjakso" and btw both are "versio 0" - is that a bug?

No, the version is set when the inspection is published. Then it would take the previously published version and add one. So you can have many inspections in draft

2021-02-22 11:30 UTC, danieldunderfelt commented
More tasks to do in this PR:

- Disable sanctions button when proceeding is not possible
- Add a processing step while sanctions are collected

2021-02-22 13:21 UTC, Divinare commented
"The user can middle click all links."

Btw for me that middle click does nothing

2021-02-23 04:47 UTC, danieldunderfelt commented
Oh, you're right! It should be a real link, but it's probably a button. Yes, in this case I'll try to make it open in a new window bu default.

2021-02-23 08:19 UTC, danieldunderfelt commented
This can be tested again. Pull both UI and server!

2021-02-23 09:24 UTC, Divinare requested changes

2021-02-23 09:24 UTC, Divinare commented on src/postInspection/SanctionsContainer.tsx
> +  }
Rename?
```
let updateSanctionsMutation = gql`
  mutation updateSanctions($sanctionUpdates: [SanctionUpdate!]!) {
  ...
```

2021-02-23 09:32 UTC, Divinare commented on src/common/table/StatefulTable.tsx
> +          />
There are two ways of implementing this: having a separate StatefulTable or filters / pagination inside Table

-> You have less Table props with StatefulTable but also one additional component which name doesn't indicate much

Not sure which one is the best at the current state but if pagination were made only in UI (backend could have row length limit like 5000), we could put filters inside Table.

2021-02-23 10:35 UTC, danieldunderfelt commented on src/common/components/Tabs.tsx
> +  default?: boolean
Not for us to decide, Reach Router uses default: https://reach.tech/router/api/RouteComponent

2021-02-23 10:42 UTC, danieldunderfelt commented on src/common/table/Table.tsx
> +    isAlwaysEditable = false,
In normal operation you have to double-click the cell to start editing it, but for sanctions I wanted the editable cell to be, well, always editable, without the need for a double-click.

Documenting the Table component is a task in itself.

2021-02-23 10:49 UTC, danieldunderfelt commented on src/common/table/Table.tsx
> +    pageState: propPageConfig,
Sure, we can use pageState.

2021-02-23 10:53 UTC, danieldunderfelt commented on src/common/table/tableUtils.tsx
> +export function useRenderCellValue() {
Well, for now. It started as something I used in other components, and it can still be used in other components. So it is a utility. TableRow renders data just as it is by default, a renderCellValue function can be set to customize it.

2021-02-23 10:54 UTC, danieldunderfelt commented on src/postInspection/SanctionsContainer.tsx
> +  }
To what and why? I don't understand this comment.

2021-02-23 11:10 UTC, danieldunderfelt commented on src/common/table/StatefulTable.tsx
> +          />
StatefulTable is a convenience component for rendering a table based on a paged/filtered/sorted response. Otherwise it would need to be done separately in sanctions and reports, and in future places that work like this.

I'm not sure what your standard for a name is. StatefulTable indicates that the table uses state and works with stateful data. A name is not documentation, it is not expected to describe everything about something. Documentation is forthcoming as soon as we arrive at a good and stable implementation.

Generally I'd like Table to be as dumb as possible and just render the rows given to it. Then we'd have container components like this to compose Table with relevant other components as needed. Sorting MUST be done in the table, but paging could be extracted. But we did agree that it goes in Table for now.

2021-02-23 11:27 UTC, danieldunderfelt commented on src/common/table/Table.tsx
> +    pageMeta: propPageMeta,
PageMeta is the data that describes how the response data is paged. If it's not paged, the Table creates internal pageMeta which is passed to the paging component for UI paging.

I'm not sure what you propose but I am all for taking the Paging stuff out from Table.

2021-02-23 11:31 UTC, danieldunderfelt commented on src/common/table/Table.tsx
> +  disablePaging?: boolean
If no paging stuff is supplied to Table, it will do UI paging internally. With this, UI paging can be disabled.

2021-02-23 12:53 UTC, Divinare commented on src/common/components/Tabs.tsx
> +  default?: boolean
Ouch. Well then a comment could be added: default?: boolean // When no children match, a route component with a default prop will render

Btw it seems like it's not using default props

2021-02-23 13:07 UTC, Divinare commented on src/postInspection/SanctionsContainer.tsx
> +  }
```
let setSanctionMutation = gql`
  mutation setSanction($sanctionUpdates: [SanctionUpdate!]!) {
    updateSanctions(sanctionUpdates: $sanctionUpdates) {
      id
      appliedSanctionAmount
    }
  }
`
```
rename as
```
let updateSanctionsMutation = gql`
  mutation updateSanctions($sanctionUpdates: [SanctionUpdate!]!) {
    updateSanctions(sanctionUpdates: $sanctionUpdates) {
      id
      appliedSanctionAmount
    }
  }
```
because setSanctionMutation and setSanction are way different than the resolver updateSanctions. The latter one is plural and set+update, well they could be the same.

2021-02-23 13:21 UTC, danieldunderfelt commented
Fixed pro and var naming related to page things.

2021-02-23 13:22 UTC, Divinare commented on src/common/table/StatefulTable.tsx
> +          />
It's true that name can't always be descriptive, didn't like it should.

Hmm I like the idea of Table being dumb and simple. What if we had dumb Table inside Table? I mean, merge the current Table.tsx and StatefulTable.tsx as StatefulTable and then extract Table.tsx out (which takes only simple props and renders a table).

2021-02-23 13:40 UTC, danieldunderfelt commented on src/common/table/Table.tsx
> +    pageState: propPageConfig,
Fixed!

2021-02-23 14:02 UTC, Divinare approved these changes
Approving at this point since this work continues in other PR's!

2021-02-23 14:03 UTC, merged