198 ability to lock user in hsl
HSLdevcom/bultti-ui pull request #63
Opened 2021-03-16 11:34 UTC by Divinare

Closes https://github.com/HSLdevcom/bultti/issues/198

2021-03-16 13:06 UTC, danieldunderfelt requested changes
A few comments, otherwise good!

2021-03-16 13:06 UTC, danieldunderfelt commented on src/util/useAuth.ts
> +  const [login, { loading: isLogingLoading }] = useMutationData<User>(loginMutation)
Typo?

2021-03-16 13:06 UTC, danieldunderfelt commented on src/util/useAuth.ts
> +          setIsLoginFailed(true)
```suggestion
          setErrorMessage(text('login_failed'))
```
Can't the message be set here? A new state variable for this seems excessive.

2021-03-16 13:20 UTC, Divinare commented on src/util/useAuth.ts
> +          setIsLoginFailed(true)
Hmm true! This code changed a bit on the way and didn't think setting it here after setIsLoginFailed variable was made!

2021-03-16 13:23 UTC, Divinare commented
Review fixes done

2021-03-17 03:45 UTC, danieldunderfelt approved these changes
LGTM! The typo fix went in a bit of a wrong direction, but I'll just merge the suggested changes.

2021-03-17 03:45 UTC, danieldunderfelt commented on src/util/useAuth.ts
> +  const [login, { loading: isLoggingLoading }] = useMutationData<User>(loginMutation)
```suggestion
  const [login, { loading: isLoginLoading }] = useMutationData<User>(loginMutation)
```

2021-03-17 03:45 UTC, danieldunderfelt commented on src/util/useAuth.ts
> +  return [authState, isLoggingLoading]
```suggestion
  return [authState, isLoginLoading]
```

2021-03-17 03:50 UTC, merged