WIP: 235 contract validation fixes
HSLdevcom/bultti-ui pull request #64
Opened 2021-03-19 10:59 UTC by Divinare

Closes https://github.com/HSLdevcom/bultti/issues/235

A bit more work required in this task; have to lock toggling off procurementUnitIds in contract form that are used in preInspection which state !== 'draft', plan:

- when preInspection is saved from in_review -> draft, clear procurementUnitContractsMap
- when preInspection is saved from draft -> in_review, update procurementUnitContractsMap
- at contract form, make a @query for usedContractProcurementUnitsIds
  - prevent toggling off checkbox which procurementUnitId is found from queried usedContractProcurementUnitsIds
- when a contract is saved, query usedContractProcurementUnitsIds and make sure procurementUnitIds that are toggled on, aren't found from usedContractProcurementUnitsIds

2021-03-23 11:20 UTC, danieldunderfelt commented
Testing notes:

- UI could also validate that the startDate < endDate and vice versa

2021-03-24 04:46 UTC, danieldunderfelt requested changes
I had an inspection that was IN_REVIEW, but I could still change the dates of the contract. This rendered the inspection invalid.

The UI should do the following:
- block changing of dates that would mess with any non-draft inspections
- UI validations for startDate < endDate (you can use the min/max props of the date input)

I also got the dirty-form navigation alert after saving units on a new contract.

2021-03-24 04:46 UTC, danieldunderfelt commented on src/contract/ContractEditor.tsx
> +      return <div />
```suggestion
      return <React.Fragment />
```

Is the way to return an empty thing which is still a React element.

2021-03-24 04:46 UTC, danieldunderfelt commented on src/contract/ContractProcurementUnitsEditor.tsx
> +          .map((unit) => unit.id)
I was able to deselect units while they were included in an inspection which was IN_REVIEW. I suggest moving this part to the start of the component and checking `unselectableUnitOptionIds` always when toggling a unit. Now there is no check in the toggle handler if the unit can be toggled.

2021-03-24 05:14 UTC, danieldunderfelt commented on src/contract/ContractProcurementUnitsEditor.tsx
> +          .map((unit) => unit.id)
Although I'm pretty sure I created the inspection while being on the PR branch, it didn't have the unit-contract map. I created a new inspection and then it worked as it should have!

I would still suggest the change, but it's not very critical.

2021-03-24 09:14 UTC, Divinare commented
New features need to be implement in this task:
3) Contract dates cannot overlap
4) Make contract startDate as uneditable

2021-03-29 10:21 UTC, Divinare commented
The spec for implenting things related to this is the air, it seems not smart trying to iterate all of this when we aren't even sure of how things should go. This is why we should stop here (leave it in a stable state though!)

--> Left for future tasks:
1) block changing of dates with any non-draft inspections
  - maybe make startDate as uneditable
  - get minimum endDate for contract
2) tests to "get contract date candidates"

What was done here?
0) Review fixes done
1) Contract's cant overlap by clicking "Sopimuksessa mukana"
 - HOWEVER, if you edit contract dates, this can cause contracts to overlap. I think we need lock specbefore going any further with this.
2) You have a temprorary button to init inspection.procurementUnitContractMap

2021-03-30 08:21 UTC, merged