WIP: Started using new calendar component: react-datepicker
HSLdevcom/bultti-ui pull request #68
Opened 2021-04-01 13:45 UTC by Divinare

Closes https://github.com/HSLdevcom/bultti/issues/240

Still WIP. Basic date selection seems to work, still need to do plenty of things (left TODO comments that i'll implement here)

![new_calendar](https://user-images.githubusercontent.com/1419296/113303290-98a6f780-9309-11eb-9c56-57033e370b4b.png)

2021-04-14 08:18 UTC, danieldunderfelt requested changes
Many comments and improvement suggestions. Some are not critical but all are good practise.

2021-04-14 08:18 UTC, danieldunderfelt commented on src/common/input/DatePicker.tsx
> +}
```suggestion
// Define in util/dayType.ts helper:

export const dayTypes = ['Ma', 'Ti', 'Ke', 'To', 'Pe', 'La', 'Su']

export function getDayTypeFromDate(date: string | Date): string {
  if (!date) {
    return ''
  }

  let dateObj = getDateObject(date)
  return dayTypes[getISODay(dateObj) - 1]
}

// Suggestion for this function:

function isDateTypeAllowed(date: Date, acceptableDayTypes?: AcceptableDayType[]) {
  if (!acceptableDayTypes || acceptableDayTypes.length === 0) {
    return true
  }

  let dayTypeOfDate = getDayTypeFromDate(date)
  return acceptableDayTypes.includes(dayTypeOfDate)
}
```

While this type of implementation is quite readable, it is very duplicated and can be written more tersely. This is my suggestion which is similar to a function in the server codebase.

2021-04-14 09:05 UTC, Divinare commented on src/common/input/DatePicker.tsx
> +    onChange(newDate ? format(newDate, INPUT_DATE_FORMAT) : null)
Hmm, for me 
```
if (!newDate && !isEmptyValueAllowed) {
    return
}
```
is maybe slightly readable but idc, changed to your format anyway

2021-04-14 09:28 UTC, Divinare commented on src/common/input/DatePicker.tsx
> +  }
Hmm, maybe it could be outside the component yeah. It was before but then I realized it needed acceptableDayTypes which I didn't want to give as param (because then you have to remember to pass it in as param). But for understandability for what this func does, it's better to give acceptableDayTypes as props. Now just you must not forget to pass acceptableDayTypes in

2021-04-14 09:31 UTC, Divinare commented on src/common/input/DatePicker.tsx
> +  }
Also it's like a helper function of DatePicker so hiding it outside of the component might be a good idea :P

2021-04-14 09:36 UTC, Divinare commented on src/common/input/DatePicker.tsx
> +  }
I'm not really fan of useCallback unless really needed. The calendar seems fast enough for me...

2021-04-14 09:38 UTC, Divinare commented on src/common/input/DatePicker.tsx
> +  }
Added one extra spacing

2021-04-14 09:39 UTC, Divinare commented on src/common/input/DatePicker.tsx
> +type AcceptableDayType = 'mo' | 'tu' | 'we' | 'th' | 'fr' | 'sa' | 'su'
Okay if so, I can switch them to Ma, Ti, Ke, ...

2021-04-14 12:06 UTC, Divinare commented on src/common/input/DatePicker.tsx
> +}
Refactored the function but didn't make an util for it (it would only save 1 line of code, I think it's ok now.

2021-04-14 12:30 UTC, Divinare commented
Review fixes done ^

2021-04-15 04:32 UTC, danieldunderfelt commented on src/common/input/DatePicker.tsx
> +    onChange(newDate ? format(newDate, INPUT_DATE_FORMAT) : null)
Yeah, that one would also have been good!

2021-04-15 04:33 UTC, danieldunderfelt commented on src/common/input/DatePicker.tsx
> +  }
That's right, I missed the use of the `acceptableDayTypes` prop! But yes, no problem with passing it as a parameter. If it's not optional it shouldn't be forgotten. Good solution!

2021-04-15 04:37 UTC, danieldunderfelt commented on src/common/input/DatePicker.tsx
> +  }
I really don't like unnecessarily nested ifs 😣  if the reason is readability I don't think it adds any of that, using `&&` is more than readable.

2021-04-15 04:39 UTC, danieldunderfelt commented on src/common/input/DatePicker.tsx
> +type AcceptableDayType = 'mo' | 'tu' | 'we' | 'th' | 'fr' | 'sa' | 'su'
Ah yes, I had forgotten they were in constants!

2021-04-15 04:40 UTC, danieldunderfelt commented on src/common/input/DatePicker.tsx
> +}
Ok cool, util is indeed not really necessary unless there are other users of the function. The idea was to mirror the code in the server repo.

2021-04-15 04:43 UTC, danieldunderfelt commented
Good stuff! I'm still hung up on the nested if in the `trimInputString` function though, so I would still like to see that fixed before merging.

2021-04-15 06:54 UTC, Divinare commented
Ah yeah sorry, didn't see that nested if until now! Fixed it thanks!

2021-04-15 07:16 UTC, merged