245 hfp optimization
HSLdevcom/bultti-ui pull request #70
Opened 2021-04-12 09:06 UTC by danieldunderfelt

Mostly schema updates related to https://github.com/HSLdevcom/bultti/issues/245

Backend PR: https://github.com/HSLdevcom/bultti/pull/247

2021-04-14 13:29 UTC, Divinare requested changes
Just two comments, otherwise LGTM!

2021-04-15 04:26 UTC, danieldunderfelt commented on src/inspection/InspectionConfig.tsx
> +  let onChangeInspectionDate = useCallback((startDate: Date, endDate: Date, id?: string) => {
The ID is undefined for pre-inspections.

2021-04-15 04:29 UTC, danieldunderfelt commented on src/inspection/inspectionDate/InsectionDateList.tsx
> +        <LoadingDisplay loading={isLoading} />
No, the whole list was jumping around and flashing when refreshing, it was very annoying. I'll add a check for "isLoading" to the empty message so it won't show when loading.

2021-04-15 05:49 UTC, Divinare commented on src/inspection/InspectionConfig.tsx
> +  let onChangeInspectionDate = useCallback((startDate: Date, endDate: Date, id?: string) => {
Ah yeah... Forgot that InspectionSelectDates serves both pre and post inspections

2021-04-15 06:34 UTC, Divinare approved these changes

2021-04-15 09:15 UTC, merged