229 test data
HSLdevcom/bultti-ui pull request #81
Opened 2021-04-28 05:24 UTC by danieldunderfelt

UI PR for task https://github.com/HSLdevcom/bultti/issues/229

Server PR: https://github.com/HSLdevcom/bultti/pull/267

- Admin page for controlling test data
- Schema updates

2021-04-29 11:26 UTC, Divinare requested changes
* There was "WIP: hide test data for normal users" - is it done?
* Filter out "Testiliikennöitsijä A"

I would hope generated test data would have:
* 10 000m metriosuus per vehicle
* ages: vehicle ages: 1v, 1v, 10v, 10v
* why is there 3 vehicles in "Kaavion ajoneuvot päivätyypeittäin" - shouldn't there be 4?
* why is "Kaavion ajoneuvot kalustotyypeittäin" table empty?

![testData_preInspection](https://user-images.githubusercontent.com/1419296/116543105-1ef92e00-a8f6-11eb-8ddd-01e12ade2139.png)

2021-04-30 03:56 UTC, danieldunderfelt commented on src/page/AdminPage.tsx
> +    skip: removeInspectionId.length < 36,
The length of a valid UUID. The idea is to not fetch the inspection preview with an incomplete UUID. I'll add a comment!

2021-04-30 03:58 UTC, danieldunderfelt commented on src/page/AdminPage.tsx
> +    nextFetchPolicy: !removeInspectionId ? 'network-only' : 'cache-first',
I don't think this matters at all in any way.

2021-04-30 06:24 UTC, Divinare approved these changes
LGTM!

2021-04-30 10:20 UTC, merged