144 upgrade typescript and eslint
HSLdevcom/bultti-ui pull request #87
Opened 2021-05-05 11:09 UTC by danieldunderfelt

Closes https://github.com/HSLdevcom/bultti/issues/114

- Start using eslint and bring over same rules as in server
- Update Typescript
- Fix types throughout the app

2021-05-06 07:33 UTC, Divinare requested changes
Well done! Nearly LGTM, left some questions

Good that we have now more typing and `any` is replaced with `unknown`

2021-05-06 07:33 UTC, Divinare commented on .eslintrc.js
> +    ecmaVersion: 2020, // Allows for the parsing of modern ECMAScript features
Tested having 2021, at least it works - didn't give any new errors

2021-05-07 07:26 UTC, danieldunderfelt commented on .eslintrc.js
> +    ecmaVersion: 2020, // Allows for the parsing of modern ECMAScript features
Sure, but it doesn't really matter as CRA is not really on the bleeding edge.

2021-05-07 07:27 UTC, danieldunderfelt commented on codegen.yml
> +schema: 'schema.graphql'
Sure!

2021-05-07 07:29 UTC, danieldunderfelt commented on codegen.yml
> +      defaultScalarType: 'string'
The default was `any`, now it is `string`. Much better, no?

We have only one custom scalar and it is a string. If we create more in the future which are not strings, `typescript-operation` allows for defining each scalar separately. I just don't see a reason to do that currently as the default works fine.

2021-05-07 07:58 UTC, merged