WIP 268 fix unsaved form warning
HSLdevcom/bultti-ui pull request #90
Opened 2021-05-11 03:24 UTC by danieldunderfelt

Issue: https://github.com/HSLdevcom/bultti/issues/268

No server PR.

Refactor the unsaved form feature and switch to react-router to make it more integrated. Reach-router cannot prevent transitions.

- Refactor unsaved form feature
- Switch to react-router
- Implement navigation blockers with react-router

2021-05-11 10:39 UTC, Divinare requested changes
Nice work! I like how the prompt is implemented. Left just a few minor comments

Testing:

* Prompting seems to work in each form!

* New idea (this should be implemented in a new card): how about adding "disabledText" props to a button so that user could hover over grey button and see the text OR click the button and get notification
  * e.g. [greyed lähetä tarkastettavaksi] --> "Sinulla on tallentamattomia muutoksia. Tallenna tai hylkää ne ennen lähetystä tarkastettavaksi"

2021-05-12 04:10 UTC, danieldunderfelt commented on src/util/urlValue.ts
> +export function pathWithQuery(path = '', location?: HasQueryString | string) {
Excluded query params really doesn't need to come from env. And I don't see the value in combining the two functions.

2021-05-12 04:13 UTC, danieldunderfelt commented on src/util/useAuth.ts
> +      setUrlValue(history, 'role', null)
Sure, but this isn't really meant to be a general interface for the search string. It's for storing state values in the URL, and the mechanic happens to be the search string. I don't feel that we need to follow any official naming, and it's better to keep it as a "domain" name to not give the impression that it IS a general interface for the search string.

2021-05-12 04:14 UTC, danieldunderfelt commented on src/state/stateContext.tsx
> +      message: 'Authentication expired or invalid. Please log in again.',
Yes, I'll add it!

2021-05-12 04:16 UTC, danieldunderfelt commented on src/util/urlValue.ts
> +export function pathWithQuery(path = '', location?: HasQueryString | string) {
Changed the name of the method to `getPathWithSearch` to reflect that it works with the search string.

2021-05-12 04:23 UTC, merged