WIP 271 fix sanction report percentages
HSLdevcom/bultti-ui pull request #91
Opened 2021-05-11 05:50 UTC by Divinare

Closes https://github.com/HSLdevcom/bultti/issues/271

2021-05-17 07:14 UTC, danieldunderfelt commented
> I would also get rid of sanctionSummaryTransform() in frontend and move the logic in backend. We would return rows that don't have duplicated procurementUnitIds.

> Btw, I know there was this comment "The reason for this is that the sanctionReasons and sanction amounts are
dynamic, and theGraphQL response fields must be regular." - is that the reason why we need sanctionSummaryTransform() at frontend side?

Indeed, not possible to have dynamic columns with GraphQL. There's not really any logic in the UI, it just combines the rows by unit and creates the sanction reason/amount columns.

The point of this report is to mimic an important report that exists as an Excel file in old Bultti.

2021-05-19 10:38 UTC, danieldunderfelt commented
> What about making a separate report for each sanction type? It could show each sanction row and the TOTAL numbers below (there is no other way than this to actually show the OperatingAreaName except showing sanction rows invidually in UI)

Current reports already show the things that lead to sanctions, but if the users want a more sanction-focused report for each issue we can certainly do that.

2021-05-19 10:39 UTC, danieldunderfelt commented
> Also if BE's createSanctionSummaryReportData() output data was nicer, we could utilize the same method when sending sanctions to KOLA in #59

This function is for creating the report. If a similar function is needed, common logic should be extracted. I don't think this should be used for anything else than creating the report.

2021-05-19 10:51 UTC, Divinare commented on src/report/cellHighlight.ts
> +function shouldHighlightCell(rowItem, key: string): boolean {
rowItem currently has `any` type but I didn't know how to provide one

2021-05-19 10:54 UTC, Divinare commented on src/common/table/TableRow.tsx
> +                : undefined
I broke row highlighting when a vehicle is added to preInspection unit's equipmentList. Not quite sure how to support that and cellHighlighter at the same time. Didn't have time to look into this yet

2021-05-20 03:27 UTC, danieldunderfelt requested changes
Good work, but left some minor comments!

2021-05-20 03:27 UTC, danieldunderfelt commented on src/common/table/tableUtils.tsx
> -        </span>
Ok, if it works without the styling...

2021-05-20 03:27 UTC, danieldunderfelt commented on src/common/table/Table.tsx
> +  cellHighlighter?: (item: TableRowWithDataAndFunctions<ItemType>, key: string) => boolean
I think the cell highlight function should follow the same format as the pre-existing `highlightRow`. It would be more consistent if it were named `highlightCell`.

2021-05-20 03:27 UTC, danieldunderfelt commented on src/report/ReportContainer.tsx
> +      }
Could be combined with the continue condition above.

2021-05-20 03:27 UTC, danieldunderfelt commented on src/report/cellHighlight.ts
> +function shouldHighlightCell(rowItem, key: string): boolean {
This function is very specific to the sanction summary report, so it should be named accordingly (eg. `shouldHighlightSanctionSummaryReportCell`). Then you can also set a static type: `TableRowWithDataAndFunctions<SanctionSummaryReportData>`.

2021-05-20 03:27 UTC, danieldunderfelt commented on src/report/cellHighlight.ts
> +export const cellHighlight = {
Maybe `reportCellHighlightMap` would be a more descriptive name?

2021-05-20 03:27 UTC, danieldunderfelt commented on src/common/table/Table.tsx
> +  cellHighlighter?: (item: TableRowWithDataAndFunctions<ItemType>, key: string) => boolean
It could also return a string like `highlightRow` to enable highlighting cells with different colors. But it's an idea for the future.

2021-05-20 07:31 UTC, Divinare commented on src/report/ReportContainer.tsx
> +      }
For better readability I think separate if is better... Now you can see that the comment relates to this statement

2021-05-20 07:33 UTC, Divinare commented on src/report/cellHighlight.ts
> +export const cellHighlight = {
Yes. Also renamed reportTransforms -> reportTransformsMap

2021-05-20 07:49 UTC, danieldunderfelt commented on src/report/ReportContainer.tsx
> +      }
Fair point, either way is fine. Comments can be added to combined iffs too, though.

2021-05-20 09:55 UTC, merged