283 Show JOLA rows in post-inspection editor
HSLdevcom/bultti-ui pull request #92
Opened 2021-05-19 10:26 UTC by danieldunderfelt

Issue: https://github.com/HSLdevcom/bultti/issues/283

Server PR:

Shows JOLA rows in a new box in the post-inspection editor. No actual sanctions or reports created yet.

2021-05-19 14:00 UTC, Divinare requested changes
Seems to work, saw one JOLA-sanction in the table when used February in postInspection, then encountered a cache bug - added new card to fix it: https://github.com/HSLdevcom/bultti/issues/286

Still would like to test with a longer period

2021-05-19 14:00 UTC, Divinare commented on src/text/fi.json
> +  "postInspection_jolaPreview_description": "Näiden JOLA-rivien perusteella tehdään tähän jälkitarkastukseen sisältyvä kalustovikasanktiointi. Tämä on pelkkä esikatselu; kun tarkastus viedään sanktio
I would say:
"...lopulliset rivit haetaan JOLA:sta kun jälkitarkastus asetetaan hyväksyttäväksi."

2021-05-19 14:00 UTC, Divinare commented on src/text/fi.json
> +  "postInspection_jolaPreview_description": "Näiden JOLA-rivien perusteella tehdään tähän jälkitarkastukseen sisältyvä kalustovikasanktiointi. Tämä on pelkkä esikatselu; kun tarkastus viedään sanktio
This functionality should be quite clear for users, maybe put it behind a question mark (?)

2021-05-20 02:32 UTC, danieldunderfelt commented on src/text/fi.json
> +  "postInspection_jolaPreview_description": "Näiden JOLA-rivien perusteella tehdään tähän jälkitarkastukseen sisältyvä kalustovikasanktiointi. Tämä on pelkkä esikatselu; kun tarkastus viedään sanktio
Yes we can use the question mark! Texts written by me are mainly placeholders, feel free to change them.

2021-05-20 11:32 UTC, Divinare approved these changes

2021-05-21 06:28 UTC, merged