289 unit contract map
HSLdevcom/bultti-ui pull request #98
Opened 2021-06-07 08:39 UTC by danieldunderfelt

Issue: https://github.com/HSLdevcom/bultti/issues/289

Server PR: https://github.com/HSLdevcom/bultti/pull/329

Schema updates for the server PR. Remove temporary init contract map button.

2021-06-10 13:22 UTC, Divinare requested changes
Left 1 comment, havent tested yet

2021-06-11 03:37 UTC, danieldunderfelt commented on src/text/fi.json
> +  "POST_INSPECTION_END_DATE_NOT_IN_THE_PAST": "Jälkitarkastusjakson loppupäivä pitää olla aikaisintaan kuukausi menneisyydessä.",
It seems to come from this issue (and related PR's): https://github.com/HSLdevcom/bultti/issues/95

I can't remember where this limitation came from, but it is not needed.

2021-06-11 03:57 UTC, danieldunderfelt commented on src/text/fi.json
> +  "POST_INSPECTION_END_DATE_NOT_IN_THE_PAST": "Jälkitarkastusjakson loppupäivä pitää olla aikaisintaan kuukausi menneisyydessä.",
Removed it now.

2021-06-11 10:20 UTC, Divinare approved these changes

2021-06-11 10:36 UTC, merged